version: "3.8"

services:
  client:
    container_name: book_ms_client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/book_ms_app
      - /var/www/book_ms_app/client/node_modules
    networks:
      - app-network

  php:
    container_name: book_ms_php
    build:
      context: ./docker/php
    ports:
      - '9001:9000'
    volumes:
      - .:/var/www/book_ms_app
    networks:
      - app-network

  nginx:
    container_name: book_ms_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/book_ms_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    platform: linux/amd64
    container_name: book_ms_mysql
    image: mysql:8.0
    ports:
      - "3309:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge